version: '3'
services:
  mysql_db:
    image: mysql:5.7
    container_name: mysql_5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'skeleton_db'
#      # So you don't have to use root, but you can if you like
#      MYSQL_USER: 'user'
#      # You can use whatever password you like
#      MYSQL_PASSWORD: 'password'
#      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
#     disabling for now - https://github.com/docker-library/mysql/issues/275#issuecomment-292243855
#    volumes:
#      - ./mysql_data:/var/lib/mysql


